- hosts: clc
  vars_files:
  - vars/main.yml
  roles:
  - JohnPreston.eucalyptus-clc

- hosts: walrus
  roles:
  - JohnPreston.eucalyptus-walrus
  vars_files:
  - vars/main.yml

- hosts: cc
  vars_files:
  - vars/main.yml
  roles:
  - JohnPreston.eucalyptus-cc

- hosts: sc
  vars_files:
  - vars/main.yml
  roles:
  - JohnPreston.eucalyptus-sc

- hosts: nc
  vars_files:
  - vars/main.yml
  roles:
  - JohnPreston.eucalyptus-nc

- hosts:
  - clc
  - walrus
  - ufs
  - cc
  - sc
  - nc
  vars_files:
  - vars/main.yml
  roles:
  - JohnPreston.eucalyptus-register

